///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia, Metrosage, and project contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

////////////////////////////////////////////////////////////////////////
//
// exception.h
//
// This file was generated by XMLSpy 2016 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#pragma once

#include <string>
#include <stdexcept>
#include "AltovaDefs.h"
#include "StructInfo.h"

namespace altova
{
	class Error : public std::logic_error
	{
		const std::exception* m_inner;
		string_type m_message;
	public:
		Error(const string_type& message, const std::exception* inner = 0)
			: std::logic_error("altova::Error"), m_message(message), m_inner(inner) {}

		~Error () throw () {};

		string_type message() const { return m_message; }
		const std::exception* inner() const { return m_inner; }
	};

	class Exception : public std::runtime_error
	{
		const std::exception* m_inner;
		string_type m_message;
	public:
		Exception(const string_type& message, const std::exception* inner = 0)
			: std::runtime_error("altova::Exception"), m_message(message), m_inner(inner) {}

        ~Exception () throw () {};

		string_type message() const { return m_message; }
		const std::exception* inner() const { return m_inner; }
	};


	class InvalidArgumentException : public Exception
	{
	public:
		InvalidArgumentException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};


	/*	Exception thrown when a type conversion fails.

		Type conversions are value space conversions, lexical space to value space conversions,
		and value space to lexical space conversions.
	*/
	class ConversionException : public Exception
	{
	public:
		ConversionException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};


	/*	Exception thrown for lexical space to value space conversions. */
	class StringParseException : public ConversionException
	{
	public:
		StringParseException(const string_type& targetTypeName, const string_type& sourceValue)
			: ConversionException(_T("'") + sourceValue + _T("' could not be parsed as ") + targetTypeName)
		{}

		StringParseException(const string_type& message, const std::exception* inner = 0)
			: ConversionException(message, inner) {}
	};


	/*	Exception thrown for value space to lexical space conversions. */
	class ValueNotRepresentableException : public ConversionException
	{
	public:
		ValueNotRepresentableException(const string_type& sourceTypeName, const string_type& reason)
			: ConversionException(_T("Source value of type ") + sourceTypeName + _T(" cannot be converted to string: ") + reason)
		{}

		ValueNotRepresentableException(const string_type& message, const std::exception* inner = 0)
			: ConversionException(message, inner) {}
	};


	/*	Exception thrown when source value cannot be represented in target domain. */
	class OutOfRangeException : public ConversionException
	{
	public:
		OutOfRangeException(const string_type& sourceTypeName, const string_type& targetTypeName, const string_type& value)
			: ConversionException(_T("Source value '") + value + _T("' of type ") + sourceTypeName + _T(" cannot be converted to ") + targetTypeName)
		{}
	};



	class InvalidOperationException : public Exception
	{
	public:
		InvalidOperationException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};


	class DataSourceUnavailableException : public Exception
	{
	public:
		DataSourceUnavailableException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};

	class DataTargetUnavailableException : public Exception
	{
	public:
		DataTargetUnavailableException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};

	class TargetUpdateFailureException : public Exception
	{
	public:
		TargetUpdateFailureException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};


	class UserException : public Exception
	{
	public:
		UserException(const string_type& message, const std::exception* inner = 0)
			: Exception(message, inner) {}
	};
}

//#endif // _Altova_exception_INCLUDED_
