#pragma once



namespace qif191
{

namespace t
{	

class CCharacteristicDefinitionsType : public TypeBase
{
public:
	QIF191_EXPORT CCharacteristicDefinitionsType(xercesc::DOMNode* const& init);
	QIF191_EXPORT CCharacteristicDefinitionsType(CCharacteristicDefinitionsType const& init);
	void operator=(CCharacteristicDefinitionsType const& other) { m_node = other.m_node; }
	static altova::meta::ComplexType StaticInfo() { return altova::meta::ComplexType(types + _altova_ti_t_altova_CCharacteristicDefinitionsType); }
	MemberElement<t::CCharacteristicDefinitionBaseType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_CharacteristicDefinition> CharacteristicDefinition;
	struct CharacteristicDefinition { typedef Iterator<t::CCharacteristicDefinitionBaseType> iterator; };
	MemberElement<t::CAngleBetweenCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_AngleBetweenCharacteristicDefinition> AngleBetweenCharacteristicDefinition;
	struct AngleBetweenCharacteristicDefinition { typedef Iterator<t::CAngleBetweenCharacteristicDefinitionType> iterator; };
	MemberElement<t::CAngleCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_AngleCharacteristicDefinition> AngleCharacteristicDefinition;
	struct AngleCharacteristicDefinition { typedef Iterator<t::CAngleCharacteristicDefinitionType> iterator; };
	MemberElement<t::CAngleFromCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_AngleFromCharacteristicDefinition> AngleFromCharacteristicDefinition;
	struct AngleFromCharacteristicDefinition { typedef Iterator<t::CAngleFromCharacteristicDefinitionType> iterator; };
	MemberElement<t::CAngularCoordinateCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_AngularCoordinateCharacteristicDefinition> AngularCoordinateCharacteristicDefinition;
	struct AngularCoordinateCharacteristicDefinition { typedef Iterator<t::CAngularCoordinateCharacteristicDefinitionType> iterator; };
	MemberElement<t::CAngularityCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_AngularityCharacteristicDefinition> AngularityCharacteristicDefinition;
	struct AngularityCharacteristicDefinition { typedef Iterator<t::CAngularityCharacteristicDefinitionType> iterator; };
	MemberElement<t::CChordCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_ChordCharacteristicDefinition> ChordCharacteristicDefinition;
	struct ChordCharacteristicDefinition { typedef Iterator<t::CChordCharacteristicDefinitionType> iterator; };
	MemberElement<t::CCircularRunoutCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_CircularRunoutCharacteristicDefinition> CircularRunoutCharacteristicDefinition;
	struct CircularRunoutCharacteristicDefinition { typedef Iterator<t::CCircularRunoutCharacteristicDefinitionType> iterator; };
	MemberElement<t::CCircularityCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_CircularityCharacteristicDefinition> CircularityCharacteristicDefinition;
	struct CircularityCharacteristicDefinition { typedef Iterator<t::CCircularityCharacteristicDefinitionType> iterator; };
	MemberElement<t::CConcentricityCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_ConcentricityCharacteristicDefinition> ConcentricityCharacteristicDefinition;
	struct ConcentricityCharacteristicDefinition { typedef Iterator<t::CConcentricityCharacteristicDefinitionType> iterator; };
	MemberElement<t::CCurveLengthCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_CurveLengthCharacteristicDefinition> CurveLengthCharacteristicDefinition;
	struct CurveLengthCharacteristicDefinition { typedef Iterator<t::CCurveLengthCharacteristicDefinitionType> iterator; };
	MemberElement<t::CCylindricityCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_CylindricityCharacteristicDefinition> CylindricityCharacteristicDefinition;
	struct CylindricityCharacteristicDefinition { typedef Iterator<t::CCylindricityCharacteristicDefinitionType> iterator; };
	MemberElement<t::CDepthCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_DepthCharacteristicDefinition> DepthCharacteristicDefinition;
	struct DepthCharacteristicDefinition { typedef Iterator<t::CDepthCharacteristicDefinitionType> iterator; };
	MemberElement<t::CDiameterCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_DiameterCharacteristicDefinition> DiameterCharacteristicDefinition;
	struct DiameterCharacteristicDefinition { typedef Iterator<t::CDiameterCharacteristicDefinitionType> iterator; };
	MemberElement<t::CDistanceBetweenCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_DistanceBetweenCharacteristicDefinition> DistanceBetweenCharacteristicDefinition;
	struct DistanceBetweenCharacteristicDefinition { typedef Iterator<t::CDistanceBetweenCharacteristicDefinitionType> iterator; };
	MemberElement<t::CDistanceFromCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_DistanceFromCharacteristicDefinition> DistanceFromCharacteristicDefinition;
	struct DistanceFromCharacteristicDefinition { typedef Iterator<t::CDistanceFromCharacteristicDefinitionType> iterator; };
	MemberElement<t::CFlatnessCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_FlatnessCharacteristicDefinition> FlatnessCharacteristicDefinition;
	struct FlatnessCharacteristicDefinition { typedef Iterator<t::CFlatnessCharacteristicDefinitionType> iterator; };
	MemberElement<t::CHeightCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_HeightCharacteristicDefinition> HeightCharacteristicDefinition;
	struct HeightCharacteristicDefinition { typedef Iterator<t::CHeightCharacteristicDefinitionType> iterator; };
	MemberElement<t::CLengthCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_LengthCharacteristicDefinition> LengthCharacteristicDefinition;
	struct LengthCharacteristicDefinition { typedef Iterator<t::CLengthCharacteristicDefinitionType> iterator; };
	MemberElement<t::CLineProfileCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_LineProfileCharacteristicDefinition> LineProfileCharacteristicDefinition;
	struct LineProfileCharacteristicDefinition { typedef Iterator<t::CLineProfileCharacteristicDefinitionType> iterator; };
	MemberElement<t::CLinearCoordinateCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_LinearCoordinateCharacteristicDefinition> LinearCoordinateCharacteristicDefinition;
	struct LinearCoordinateCharacteristicDefinition { typedef Iterator<t::CLinearCoordinateCharacteristicDefinitionType> iterator; };
	MemberElement<t::CParallelismCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_ParallelismCharacteristicDefinition> ParallelismCharacteristicDefinition;
	struct ParallelismCharacteristicDefinition { typedef Iterator<t::CParallelismCharacteristicDefinitionType> iterator; };
	MemberElement<t::CPerpendicularityCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_PerpendicularityCharacteristicDefinition> PerpendicularityCharacteristicDefinition;
	struct PerpendicularityCharacteristicDefinition { typedef Iterator<t::CPerpendicularityCharacteristicDefinitionType> iterator; };
	MemberElement<t::CPointProfileCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_PointProfileCharacteristicDefinition> PointProfileCharacteristicDefinition;
	struct PointProfileCharacteristicDefinition { typedef Iterator<t::CPointProfileCharacteristicDefinitionType> iterator; };
	MemberElement<t::CPositionCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_PositionCharacteristicDefinition> PositionCharacteristicDefinition;
	struct PositionCharacteristicDefinition { typedef Iterator<t::CPositionCharacteristicDefinitionType> iterator; };
	MemberElement<t::CRadiusCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_RadiusCharacteristicDefinition> RadiusCharacteristicDefinition;
	struct RadiusCharacteristicDefinition { typedef Iterator<t::CRadiusCharacteristicDefinitionType> iterator; };
	MemberElement<t::CSquareCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_SquareCharacteristicDefinition> SquareCharacteristicDefinition;
	struct SquareCharacteristicDefinition { typedef Iterator<t::CSquareCharacteristicDefinitionType> iterator; };
	MemberElement<t::CStraightnessCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_StraightnessCharacteristicDefinition> StraightnessCharacteristicDefinition;
	struct StraightnessCharacteristicDefinition { typedef Iterator<t::CStraightnessCharacteristicDefinitionType> iterator; };
	MemberElement<t::CSurfaceProfileCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_SurfaceProfileCharacteristicDefinition> SurfaceProfileCharacteristicDefinition;
	struct SurfaceProfileCharacteristicDefinition { typedef Iterator<t::CSurfaceProfileCharacteristicDefinitionType> iterator; };
	MemberElement<t::CSurfaceProfileNonUniformCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_SurfaceProfileNonUniformCharacteristicDefinition> SurfaceProfileNonUniformCharacteristicDefinition;
	struct SurfaceProfileNonUniformCharacteristicDefinition { typedef Iterator<t::CSurfaceProfileNonUniformCharacteristicDefinitionType> iterator; };
	MemberElement<t::CSurfaceTextureCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_SurfaceTextureCharacteristicDefinition> SurfaceTextureCharacteristicDefinition;
	struct SurfaceTextureCharacteristicDefinition { typedef Iterator<t::CSurfaceTextureCharacteristicDefinitionType> iterator; };
	MemberElement<t::CSymmetryCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_SymmetryCharacteristicDefinition> SymmetryCharacteristicDefinition;
	struct SymmetryCharacteristicDefinition { typedef Iterator<t::CSymmetryCharacteristicDefinitionType> iterator; };
	MemberElement<t::CThicknessCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_ThicknessCharacteristicDefinition> ThicknessCharacteristicDefinition;
	struct ThicknessCharacteristicDefinition { typedef Iterator<t::CThicknessCharacteristicDefinitionType> iterator; };
	MemberElement<t::CThreadCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_ThreadCharacteristicDefinition> ThreadCharacteristicDefinition;
	struct ThreadCharacteristicDefinition { typedef Iterator<t::CThreadCharacteristicDefinitionType> iterator; };
	MemberElement<t::CTotalRunoutCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_TotalRunoutCharacteristicDefinition> TotalRunoutCharacteristicDefinition;
	struct TotalRunoutCharacteristicDefinition { typedef Iterator<t::CTotalRunoutCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedAngularCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedAngularCharacteristicDefinition> UserDefinedAngularCharacteristicDefinition;
	struct UserDefinedAngularCharacteristicDefinition { typedef Iterator<t::CUserDefinedAngularCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedAreaCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedAreaCharacteristicDefinition> UserDefinedAreaCharacteristicDefinition;
	struct UserDefinedAreaCharacteristicDefinition { typedef Iterator<t::CUserDefinedAreaCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedAttributeCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedAttributeCharacteristicDefinition> UserDefinedAttributeCharacteristicDefinition;
	struct UserDefinedAttributeCharacteristicDefinition { typedef Iterator<t::CUserDefinedAttributeCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedForceCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedForceCharacteristicDefinition> UserDefinedForceCharacteristicDefinition;
	struct UserDefinedForceCharacteristicDefinition { typedef Iterator<t::CUserDefinedForceCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedLinearCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedLinearCharacteristicDefinition> UserDefinedLinearCharacteristicDefinition;
	struct UserDefinedLinearCharacteristicDefinition { typedef Iterator<t::CUserDefinedLinearCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedMassCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedMassCharacteristicDefinition> UserDefinedMassCharacteristicDefinition;
	struct UserDefinedMassCharacteristicDefinition { typedef Iterator<t::CUserDefinedMassCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedPressureCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedPressureCharacteristicDefinition> UserDefinedPressureCharacteristicDefinition;
	struct UserDefinedPressureCharacteristicDefinition { typedef Iterator<t::CUserDefinedPressureCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedSpeedCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedSpeedCharacteristicDefinition> UserDefinedSpeedCharacteristicDefinition;
	struct UserDefinedSpeedCharacteristicDefinition { typedef Iterator<t::CUserDefinedSpeedCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedTemperatureCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedTemperatureCharacteristicDefinition> UserDefinedTemperatureCharacteristicDefinition;
	struct UserDefinedTemperatureCharacteristicDefinition { typedef Iterator<t::CUserDefinedTemperatureCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedTimeCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedTimeCharacteristicDefinition> UserDefinedTimeCharacteristicDefinition;
	struct UserDefinedTimeCharacteristicDefinition { typedef Iterator<t::CUserDefinedTimeCharacteristicDefinitionType> iterator; };
	MemberElement<t::CUserDefinedUnitCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_UserDefinedUnitCharacteristicDefinition> UserDefinedUnitCharacteristicDefinition;
	struct UserDefinedUnitCharacteristicDefinition { typedef Iterator<t::CUserDefinedUnitCharacteristicDefinitionType> iterator; };
	MemberElement<t::CWidthCharacteristicDefinitionType, _altova_mi_t_altova_CCharacteristicDefinitionsType_altova_WidthCharacteristicDefinition> WidthCharacteristicDefinition;
	struct WidthCharacteristicDefinition { typedef Iterator<t::CWidthCharacteristicDefinitionType> iterator; };
	QIF191_EXPORT void SetXsiType();
};



} // namespace t

}	// namespace qif191

//#endif // _ALTOVA_INCLUDED_QIFDocument_ALTOVA_t_ALTOVA_CCharacteristicDefinitionsType
