///////////////////////////////////////////////////////////////////////////////
///
/// Copyright 2018-2020, Capvidia, Metrosage, and project contributors
/// https://www.capvidia.com/
/// 
/// This software is provided for free use to the QIF Community under the 
/// following license:
/// 
/// Boost Software License - Version 1.0 - August 17th, 2003
/// https://www.boost.org/LICENSE_1_0.txt
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.

#pragma once
#include "qif191cli.h"
#include "CmmParameters.h"
#include "qif191\QifResourcesDocument.h"
#include "IResourcesDocument.h"

using System::String;
using System::Collections::Generic::IEnumerable;
using System::Collections::Generic::IReadOnlyList;

namespace Qif_1_9_1
{
/// <summary> Represents QIF 1.9.1 measurement resources document. </summary>
public ref class QifResourcesDocument : Qif::IResourcesDocument
{
public:
    QifResourcesDocument(String^ filepath);
    ~QifResourcesDocument() { this->!QifResourcesDocument(); }
    !QifResourcesDocument();

    // Gets or sets the QPId of the document
    virtual property System::String^ Qpid;

    // Save the given CMM list to the QIF document. Returns true if success.
    virtual bool Save(IEnumerable<Qif::CmmParameters^>^ cmmParameters) ;

    // Load a list of CMMs from the QIF document. Returns non-null if success.
    virtual IReadOnlyList<Qif::CmmParameters^>^ Load();

    // Error and Warning lists
    virtual property IReadOnlyList<String^>^ ErrorList { IReadOnlyList<String^>^ get(); }
    virtual property IReadOnlyList<String^>^ ErrorDetailsList { IReadOnlyList<String^>^ get(); }
    virtual property IReadOnlyList<String^>^ WarningList { IReadOnlyList<String^>^ get(); }
    virtual property IReadOnlyList<String^>^ WarningDetailsList { IReadOnlyList<String^>^ get(); }

    // Returns true if there was an error/warning
    virtual property bool HadError { bool get() { return _document->HadError(); } }
    virtual property bool HadWarning { bool get() { return _document->HadWarning(); } }

private:
    // core unmanaged object
    qif191::QifResourcesDocument* _document;


};
}
