////////////////////////////////////////////////////////////////////////
//
// StdAfx.cpp
//
// This file was generated by XMLSpy 2015r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION. -- NOTE DC 4/13/15: We can edit these files. Just make sure to merge if we regenerate.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#include "StdAfx.h"
