////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2015r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION. -- NOTE DC 4/13/15: We can edit these files. Just make sure to merge if we regenerate.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#pragma once

#if _MSC_VER < 1300
#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information
#endif

#if !defined( __GNUC__ )

#include <tchar.h>
#include <windows.h>
#define TRACE
#define ASSERT

#endif


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>




//#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information



#include <qifbase/Altova/Altova.h>
#include <qifbase/Altova/SchemaTypes.h>
#include <qifbase/Altova/AltovaException.h>
#include <qifbase/AltovaXML/XmlException.h>
#include <qifbase/AltovaXML/Node.h>
using namespace altova;


//{{AFX_INSERT_LOCATION}}

//#endif // ALTOVA_STDAFX_H_INCLUDED
